import PublicPageShell, { ArrowIcon, InfoCard } from '../components/PublicPageShell'

export default function AboutPage() {
  return <PublicPageShell eyebrow="The idea behind the interface" title="Made for the hours when discovery feels personal." intro="Midnight Anime is built around a late-night, mobile-friendly anime discovery and viewing experience. It brings catalogue context, watchlist tools, direct playback where available, and web-to-Android paths into one focused place.">
    <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <div className="relative overflow-hidden rounded-3xl border border-white/[0.08] bg-gradient-to-br from-or/15 via-white/[0.035] to-fuchsia-500/10 p-7 sm:p-10"><div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full border border-white/10 bg-white/[0.04] blur-sm" /><p className="relative font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-or">How it started</p><h2 className="relative mt-4 max-w-xl font-display text-3xl font-black sm:text-4xl">A product direction, not a made-up origin story.</h2><p className="relative mt-6 max-w-xl text-sm leading-relaxed text-white/60">Midnight Anime is shaped around a simple mission: reduce the friction between “what should I watch?” and the moment an episode starts. The experience is designed to stay clear on a small screen while still giving titles enough room to breathe.</p></div>
      <div className="rounded-3xl border border-white/[0.08] bg-white/[0.035] p-7 sm:p-10"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-or">Where it is going</p><p className="mt-5 text-sm leading-relaxed text-white/60">The product direction is to make discovery more useful, metadata more legible, and playback paths more dependable—without pretending that every title, language, or source behaves the same way.</p><a href="/wiki" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-or hover:underline">Read the wiki <ArrowIcon /></a></div>
    </section>
    <section className="mt-14"><div className="mb-7 max-w-xl"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-or">What we optimize for</p><h2 className="mt-3 font-display text-2xl font-bold">Useful details, fewer dead ends.</h2></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><InfoCard title="Clear discovery" icon="✦">Search, browse, trending views, genres, and seasonal context help you move from a mood to a title.</InfoCard><InfoCard title="Rich context" icon="◈">AniList and supported metadata sources give title pages room for artwork, status, scores, seasons, relations, and episode information.</InfoCard><InfoCard title="Flexible viewing" icon="▶">Direct playback, subtitles, dubs, and Hindi streams are presented where a supported source makes them available.</InfoCard><InfoCard title="A place to return" icon="↺">Watchlist and progress tools help signed-in viewers keep track of what is next.</InfoCard><InfoCard title="Share the moment" icon="↗">Series and episode links make it easier to send someone directly to the right context.</InfoCard><InfoCard title="Web to Android" icon="⌁">The web flow can attempt the Android app intent and fall back to a download path when the app does not open.</InfoCard></div></section>
    <section className="mt-14 rounded-3xl border border-white/[0.08] bg-black/20 p-7 text-sm leading-relaxed text-white/55 sm:p-9"><h2 className="font-display text-xl font-bold text-white">Independent by design</h2><p className="mt-3 max-w-3xl">Midnight Anime is presented here as its own product experience. References to AniList, TMDB, Android, or other services describe technical data or platform paths used where supported; they are not claims of partnership, sponsorship, licensing, or endorsement.</p></section>
  </PublicPageShell>
}
