import PublicPageShell, { InfoCard } from '../components/PublicPageShell'

const sections = [
  ['01', 'Find your next watch', 'Browse the catalogue, explore trending titles, follow genres, or use search. Anime detail pages bring together title metadata, related series, available episodes, and links into playback.'],
  ['02', 'Keep your place', 'A watchlist and progress tools are available when you sign in. Without an account, browsing and available playback can still be used, but saved progress depends on the signed-in experience.'],
  ['03', 'Choose what is available', 'Subtitle, dub, and Hindi availability varies by title and source. The player exposes supported tracks and controls; it does not promise every language for every show.'],
  ['04', 'Play directly in the browser', 'Midnight Anime can use direct media sources when available, including MP4 and M3U8/HLS playback. Playback depends on the selected source, device, browser, and network.'],
  ['05', 'Share a useful link', 'Series and episode share URLs are designed to preserve the title context and open the relevant Midnight Anime destination. Social previews use available artwork and a concise open action.'],
  ['06', 'Understand the metadata', 'AniList supplies much of the catalogue metadata and discovery data. TMDB resolution may add artwork and identifiers for supported share previews. These services are data sources, not endorsements.'],
]

export default function WikiPage() {
  return <PublicPageShell eyebrow="Midnight Anime wiki" title="A calmer way to find your way around." intro="This guide explains the product in plain language: what each area does, what depends on a source being available, and what to try when a link or player needs troubleshooting.">
    <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{sections.map(([number, title, text]) => <InfoCard key={number} title={<span className="flex items-center gap-3"><span className="font-mono text-xs text-or">{number}</span>{title}</span>} icon={<span className="font-mono text-sm font-bold">{number}</span>}>{text}</InfoCard>)}</div>
    <section className="mt-16 grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <div className="rounded-3xl border border-white/[0.08] bg-white/[0.035] p-6 sm:p-8"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-or">Troubleshooting</p><h2 className="mt-3 font-display text-2xl font-bold">When something does not open</h2><div className="mt-7 space-y-5 text-sm leading-relaxed text-white/55"><p><strong className="text-white/80">Playback stalls:</strong> try another available source, check the connection, or reload the player. A source can be unavailable without the catalogue page being broken.</p><p><strong className="text-white/80">A deep link shows an error:</strong> confirm the URL is complete, then open the web catalogue and search for the title. Direct routes are intended to work on refresh, but a source or title may have changed.</p><p><strong className="text-white/80">The Android app did not open:</strong> the web flow attempts an Android package intent. Browsers cannot reliably confirm whether an app is installed, so the safe fallback is the <a className="text-or hover:underline" href="/download">download page</a>.</p></div></div>
      <div className="rounded-3xl border border-or/20 bg-gradient-to-br from-or/15 via-white/[0.03] to-fuchsia-500/10 p-6 sm:p-8"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.2em] text-or">Account & trust</p><h2 className="mt-3 font-display text-2xl font-bold">Keep the boundaries clear.</h2><p className="mt-5 text-sm leading-relaxed text-white/55">Privacy, terms, sign-in, watchlist, and app-download flows are kept separate so you can choose what you need. Review <a className="text-or hover:underline" href="/privacy">privacy</a> and <a className="text-or hover:underline" href="/terms">terms</a> for the current site policies.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/app" className="rounded-full bg-or px-5 py-2.5 text-sm font-bold">Browse anime</a><a href="/download" className="rounded-full border border-white/15 px-5 py-2.5 text-sm font-bold hover:border-or">Get the app</a></div></div>
    </section>
  </PublicPageShell>
}
