const cfg=window.SOLO_CONFIG;let sb=null;if(window.supabase&&cfg.key&&!cfg.key.startsWith("YOUR_"))sb=window.supabase.createClient(cfg.url,cfg.key);
const demo=[["Creator Launch Pack","Templates","$24","✦"],["Aurora UI Kit","Graphics","$18","◈"],["AI Creator Prompts","AI","$12","✧"],["Sonic Texture Pack","Audio","$15","♫"],["Notion OS Pro","Templates","$29","⌘"],["Brand Identity Kit","Graphics","$32","◇"],["Developer Icon Set","Graphics","$9","⌁"],["Motion Presets","Software","$21","↯"]];
let all=demo;
const products=document.querySelector("#products"),filters=document.querySelector("#filters"),cats=document.querySelector("#cats");
function draw(){let q=document.querySelector("#search").value.toLowerCase();let active=document.querySelector(".filter.active")?.dataset.v||"All";products.innerHTML=all.filter(x=>(active==="All"||x[1]===active)&&x[0].toLowerCase().includes(q)).map(x=>`<article class="product"><div class="art">${x[3]}</div><div class="info"><div><b>${x[0]}</b><small>${x[1]} · Instant download</small></div><b>${x[2]}</b></div></article>`).join("")||"<p>No products found.</p>"}
["All","Templates","Graphics","Software","AI","Audio"].forEach((x,i)=>{let b=document.createElement("button");b.className="filter"+(!i?" active":"");b.textContent=x;b.dataset.v=x;b.onclick=()=>{document.querySelectorAll(".filter").forEach(a=>a.classList.remove("active"));b.classList.add("active");draw()};filters.append(b)});
["Templates","Graphics","AI & Prompts","Audio","Video","Software"].forEach((x,i)=>{cats.insertAdjacentHTML("beforeend",`<div class="cat" onclick="document.querySelector('#shop').scrollIntoView()"><b>${['⌘','◈','✦','♫','▶','⚙'][i]}</b><div><strong>${x}</strong><small>Explore digital products →</small></div></div>`)});
document.querySelector("#search").oninput=draw;draw();
const modal=document.querySelector("#modal");const open=()=>modal.classList.add("open");["login","sell","heroSell","sell2"].forEach(id=>document.getElementById(id)?.addEventListener("click",open));document.querySelector("#close").onclick=()=>modal.classList.remove("open");
document.querySelector("#auth").onsubmit=async e=>{e.preventDefault();let s=document.querySelector("#status");if(!sb){s.textContent="Add the Supabase publishable key in js/config.js.";return}let email=document.querySelector("#email").value,password=document.querySelector("#password").value;let r=await sb.auth.signInWithPassword({email,password});if(r.error){let reg=await sb.auth.signUp({email,password});s.textContent=reg.error?reg.error.message:"Account created. Check your email."; }else{modal.classList.remove("open");location.href="dashboard/index.html"}};
